export const BIZ_BOTS_CONSTANTS = {
  REFRESH_INTENTS_SEARCH_RESULTS: 'REFRESH_INTENTS_SEARCH_RESULTS',
  REFRESH_BOTS_SEARCH_RESULTS: 'REFRESH_BOTS_SEARCH_RESULTS',
  REFRESH_CATEGORY_SEARCH_RESULTS: 'REFRESH_CATEGORY_SEARCH_RESULTS',
  REFRESH_MODELS_SEARCH_RESULTS: 'REFRESH_MODELS_SEARCH_RESULTS'
};
